apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env: 
    - name: MYSQL_ROOT_PASSWORD
      value: "kaizen"
    - name: MYSQL_DATABASE
      value: "mydb"
    - name: MYSQL_USER
      value: "mydbuser"
    - name: MYSQL_PASSWORD
      value: "mydbpass"